// author: Denis Brisson

// This script allow to progress through the quiz by displaying the question and checking the answer. It also display a timer.

//This array stores the different questions of the quiz.
const allQuestions = [{
  question: "How many tons of electronical waste is dicarded every year ?",
  choices: ["15 million", "800 thousands", "50 million", "30 million",
    "4 million"
  ],
  correctAnswer: 2,
  explanation: "50 millions tons, this is a lot ..."
}, {
  question: "On average a desktop that is turned on 2920 hours a year emits 0,5kg of CO2 per : ",
  choices: ["week", "month", "day", "second", "year"],
  correctAnswer: 2,
  explanation: "day ! On average a desktop in Europe (with loudspeakers and printer usage) uses 200W/hour; used 8 hours a day this means an emission of 175kg of CO2 per year. This do not include the manufacture emissions and many other features."
}, {
  question: "Which country emits the most carbon dioxide gas ?",
  choices: ["USA", "India", "Russia", "China"],
  correctAnswer: 3,
  explanation: " China ... With aproximately 10 billion metric tons of CO2 emissions, the country is also by far the largest Silicon producer. About 58% of the total energy generated by China in 2019 came from coal alone."
}, {
  question: "Bitcoin yearly electricity consumption is equivalent to Sweden's (131TWh), how about the global banking system ?",
  choices: ["100TWh", "260TWh", "150TWh", "200TWh"],
  correctAnswer: 1,
  explanation: "260 TWh. The global banking system is an old institution which consumes a lot of energy, proportionnally the Bitcoin cryptocurrency consume much more due to its mining process ADD LINK !!!"
}, {
  question: "On average a standard email CO2 emmission is about 4g, how much for an email with attachments ? ",
  choices: ["50g", "10g", "25g", "10kg"],
  correctAnswer: 0,
  explanation: "50g ... This might not initially seem like a lot, but when you consider the number of emails sent and received, it’s easy to see how this can add up. How many emails are resting in your mailbox ? Time to take action! You can start by deleting the ones you don't need and unsubscribe from email newsletters and other mailing list you don't read !"
}, {
  question: "How much water is used to manufacture one laptop? (in litres)",
  choices: ["700", "190,000", "50,000", "4,000", "28,000"],
  correctAnswer: 1,
  explanation: "190,000 litres of water ! This is enough drinking water for over 700 years for the average USA citizen. (country with the highest domestic consumption...)"
}, {
  question: " A PC lifespan is around 5 years nowadays, what about smartphones ?",
  choices: ["2y", "10y", "1y", "3y"],
  correctAnswer: 3,
  explanation: "3 years... Smartphones technology grows very fast, our phones become outdated while the manufacturers sell new model every year... Is there a solution against planned obsolescence? Have a look to 'Fairphones' ! "
}];

// Declaring variables for later usage.
const nextBtn = document.getElementById('myBtn');
var pointerQuestion = 0;
var correctOnes = 0;
var allSeconds = 0;

var quizForm = document.getElementById('quiz');
var congratsDiv = document.getElementById('congrats');
var radioButtons = document.getElementsByName('radioOption');
var index = 0;
var minutesLabel = document.getElementById("minutes");
var secondsLabel = document.getElementById("seconds");


function startFunc() {
  if (pointerQuestion === 0) {
    console.log(nextBtn)
    nextBtn.innerHTML = "GO !"
  }
}

// This function randomize the content order's of an array. Here the questions so that the user do not get used to a specific order if he wishes to redo the quiz.
function randomizeQs(array) {
  for (var i = array.length - 1; i > 0; i--) {

    var j = Math.floor(Math.random() * (i + 1));

    var temp = array[i];
    array[i] = array[j];
    array[j] = temp;
  }

  return array;
}

//Randomizing the array allQuestions.
randomizeQs(allQuestions);


function askQuestion() {
  var choices = allQuestions[pointerQuestion].choices;
  var question = allQuestions[pointerQuestion].question;
  if (pointerQuestion < allQuestions.length) {
    if (pointerQuestion === 0) {
      setInterval(time, 1000);
    }
    nextBtn.innerHTML = "Next";
    quizForm.innerHTML = "<h1>" + question + "</h1>" + "<br>";
    for (var i = 0; i < choices.length; i++) {
      quizForm.innerHTML +=
        "<label id='radio'><input type='radio' name='radioOption' value='" +
        choices[i] + "'/>" + choices[i] + "</label>" + "   ";
    }
    if (pointerQuestion == allQuestions.length - 1) {
      nextBtn.innerHTML = "End the Quiz";
    } else if (pointerQuestion > allQuestions.length - 1) {
      showResults();
    }
  }
}

//This function checks if the given answer is correct or false, if it is correct t appends a check logo to the question and a cross if incorrect.
function checkRadios() {

  if (radioButtons.length > 1) {

    var checked = false;
    for (var i = 0; i < radioButtons.length; i++) {
      var radio = radioButtons[i];

      if (radio.checked) {

        var index = [i];
        if (i === allQuestions[pointerQuestion].correctAnswer) {
          correctOnes++;
          allQuestions[pointerQuestion].question =
            "<span style='color: green;'>&#10003;</span>  " + allQuestions[
              pointerQuestion].question;

        } else {
          allQuestions[pointerQuestion].question =
            "<span style='color: red;'>&#10007;</span>   " + allQuestions[
              pointerQuestion].question;
        }
        if (pointerQuestion < allQuestions.length - 1) {
          pointerQuestion++;
        } else {
          //call showResults function if there no question left.
          showResults();
          return false;
        }
        break;
      }
    }
    if (document.getElementsByName('radioOption').checked == false) {
      alert('nothing is checked')
    }

  }
  askQuestion();
}

// When the windows is firstly loaded startFunc is called.
window.onload = startFunc();
// This statement calls the checkRadios function when the
nextBtn.addEventListener('click', checkRadios);

function showResults() {
  timer.remove();
  quizForm.innerHTML = "<br><h1>You got " + correctOnes + "/" + allQuestions.length +
    " in " + Math.floor(allSeconds / 60) + " minutes and " + allSeconds % 60 +
    " seconds !" + "</h1>";
  nextBtn.innerHTML = "View Answers";
  if (correctOnes >= 5) {
    congratsDiv.innerHTML = "<h2>BRAVO</h2>";
  } else if (correctOnes < 4) {
    congratsDiv.innerHTML = "<h2>You can do better next time </h2>";
  } else if (correctOnes === 0) {
    congratsDiv.innerHTML = "<h2>Thats not good ...</h2>";
  } else if (correctOnes === allQuestions.length) {
    congratsDiv.innerHTML = "<h2>Impressive :0 </h2>";
  }
  nextBtn.onclick = function showAnswers() {
    quizForm.innerHTML = "   ";
    nextBtn.remove();
    for (let i = 0; i < allQuestions.length; i++) {
      quizForm.innerHTML += "<h1>" + allQuestions[i].question + "</h1>" +
        "<br>";
      quizForm.innerHTML += "<h2>" + allQuestions[i].explanation + "</h2>" +
        "<br>" + "_______________________________________";
    }

  };
}

/// Add one to the allSeconds counter every second and associate the number of seconds and minutes into the html.
function time() {
  ++allSeconds;
  secondsLabel.innerHTML = pad(allSeconds % 60);
  minutesLabel.innerHTML = pad(parseInt(allSeconds / 60));
}

function pad(value) {
  var valueString = value + "";
  if (valueString.length < 2) {
    return "0" + valueString;
  } else {
    return valueString;
  }
}
